<?php
/**
 * Implements hook_library_info_alter().
 */
use Drupal\Core\Url;

function dss_readspeaker_library_info_alter(&$libraries, $extension) {
  //Get Config vals
  $config = \Drupal::config('dss_readspeaker.credentials');
  $customerid = $config->get('customerid');
  $query = array('pids' => 'wr', 'notools' => 1);

  // Option to disable the pop up player
  $popupplayer = $config->get('popupplayer');
  if (!$popupplayer) {
    $query['disable'] = 'popupplayback';
  }

  // Is it http or https?
  $proto = 'http';
  if (isset($_SERVER['HTTPS'])) {
    if ($_SERVER['HTTPS'] != '') $proto = 'https';
  }

  // Library in ReadSpeaker's script from CDN
  $url = \Drupal\Core\Url::fromUri($proto.'://cdn1.readspeaker.com/script/'. $customerid.'/webReader/webReader.js', array('query' => $query, 'absolute' => TRUE))->toString();
  $libraries['dss-readspeaker']['js'][$url] = array('type' => 'external');

  return $libraries;
}
