<?php
/**
 * Implements hook_library_info_alter().
 */
use Drupal\Core\Url;

function dss_readspeaker_library_info_alter(&$libraries, $extension) {
  //Get Config vals
  $config = \Drupal::config('dss_readspeaker.credentials');
  $customerid = $config->get('customerid');
  $region = $config->get('region');

  $query = array('pids' => 'embhl');

  // Is it http or https?
  $proto = 'http';
  if (isset($_SERVER['HTTPS'])) {
    if ($_SERVER['HTTPS'] != '') $proto = 'https';
  }

  // Library in ReadSpeaker's script from CDN
  $url = \Drupal\Core\Url::fromUri($proto.'://f1-'.$region.'.readspeaker.com/script/'. $customerid.'/ReadSpeaker.js', array('query' => $query, 'absolute' => TRUE))->toString();
  $libraries['dss-readspeaker']['js'][$url] = array('type' => 'external');

  return $libraries;
}
